baseURL = "https://BIRhrt.github.io/hindi-finance-blog/"
languageCode = "hi-in"
title = "पैसा और योजना"  # Money & Schemes -- change to your own site name
theme = "PaperMod"
paginate = 10

[params]
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  defaultTheme = "auto"

[params.analytics.google]
  SiteVerificationTag = "Ec2QYL1BlegCGmpeCZCZSMWjc4nx95MUi5DtS0QZe78"

[[menu.main]]
  name = "होम"
  url = "/"
  weight = 1

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 2

[[menu.main]]
  name = "Privacy Policy"
  url = "/privacy-policy/"
  weight = 3

[markup.goldmark.renderer]
  unsafe = true
